import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import AppLayout from '../components/AppLayout/index'

export default function Home() {
  return (
    <div className={styles.body}>
      <Head>
        <title>Clon de twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout >
        <h1 className={styles.title}>
          <a href="https://nextjs.org">Devter</a>
        </h1>
      </AppLayout>
    </div>
  )
}
